version: "3.8"

services:
  postgres:
    image: postgres:11.5
    ports:
    - "6556:5432"
    environment:
      POSTGRES_PASSWORD: thisismysecurepassword
    volumes:
    - $HOME/docker/volumes/AsdProject/postgres:/var/lib/postgresql/data
    shm_size: 512mb