# Generated by Django 2.2.6 on 2023-03-07 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0006_boardfollowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.Board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BoardFollowing',
        ),
        migrations.AddField(
            model_name='list',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.Board'),
        ),
    ]
