# Generated by Django 2.2.6 on 2023-03-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20230307_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='privacy',
        ),
    ]
