# Generated by Django 2.2.6 on 2023-03-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_remove_board_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
