# Generated by Django 2.2.6 on 2023-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_alter_board_id_alter_card_id_alter_joinrequest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
