# Generated by Django 4.1.7 on 2023-03-10 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_auto_20230308_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 19, 9, 54, 133606)),
        ),
    ]
