# Generated by Django 4.1.7 on 2023-03-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_auto_20230309_0206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='CardsList',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='card_list',
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
