# Generated by Django 4.1.7 on 2023-03-10 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_card_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='CardsList',
        ),
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 20, 14, 59, 302312)),
        ),
    ]
