# Generated by Django 4.1.7 on 2023-03-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_alter_card_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
