# Generated by Django 4.1.7 on 2023-03-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0020_alter_card_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='card_list',
        ),
    ]
