# Generated by Django 4.1.7 on 2023-03-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_board_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.board'),
        ),
    ]
