# Generated by Django 4.1.7 on 2023-03-07 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_boardfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='color',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='privacy',
            new_name='visibility',
        ),
        migrations.RemoveField(
            model_name='card',
            name='board',
        ),
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 6, 57, 39, 770837)),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.board')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspace.list'),
            preserve_default=False,
        ),
    ]
