# Generated by Django 4.1.7 on 2023-03-07 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_rename_color_board_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 14, 15, 58, 579672)),
        ),
    ]
