name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Install Dependencies
      run: |
        source ~/env/bin/activate && pip install -r ./backend/pip-requirements.txt
    - name: Run Tests
      run: |
        cd backend && python manage.py test
    - name: Run Server
      run: |
        sudo systemctl restart backend
