name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Pull Github
      run: |
        cd ~/ASD-Project/backend && git pull
    - name: Install Dependencies
      run: |
        source ~/env/bin/activate && pip install -r /home/ubuntu/ASD-Project/backend/pip-requirements.txt
    - name: Run Migrations
      run: |
        cd /home/ubuntu/ASD-Project/backend && source ~/env/bin/activate && python manage.py migrate
    - name: Run Tests
      run: |
        cd /home/ubuntu/ASD-Project/backend && source ~/env/bin/activate && python manage.py test
    - name: Run Server
      run: |
        sudo systemctl restart backend
